apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adc-deployment-template
  title: Google Cloud ADC component template
  description: Deploy a component with Google Cloud ADC
  tags:
    - gcp
    - adc
spec:
  owner: group:infrastructure
  type: service
  presentation:
    buttonLabels:
      reviewButtonText: Verify
      createButtonText: Deploy
  parameters:
    - title: Fill in component information
      required:
        - name
      properties:
        dependsOn:
          title: Related Component or Resource
          description: Catalog entity which the component relates to (Component, Resource)
          type: string
          ui:field: OwnedEntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - Component
              - Resource
        name:
          type: string
          description: Unique name for the component
          ui:field: EntityNamePicker
          ui:options: {}
        description:
          title: Description
          description: A description for the component
          type: string
          ui:options: {}
        tags:
          type: array
          ui:field: EntityTagsPicker
          ui:options:
            kinds: []
            showCounts: true
    - title: Select ADC template
      required:
        - adcTemplate
      properties:
          adcTemplate:
                title: ADC template
                type: string
                description: The ADC template to use
                ui:field: ADCTemplateSelector
  steps:
    - id: deploy
      action: gcloud:adc:deploy
      name: Deploy ADC selected template
      input:
        adcTemplate: ${{ parameters.adcTemplate }}
        adcToken: ${{ secrets.googleOAuthToken }}
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.name }}
            description: ${{ parameters.description }}
            tags: ${{ parameters.tags }}
          spec:
            type: service
            lifecycle: production
            owner: user:${{ user.entity.metadata.name }}
            dependsOn:
              - ${{ parameters.dependsOn }}
  output:
    links:
      - title: Google Cloud Resource Link
        icon: cloud
        url: ${{ steps.deploy.output.resourceUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.deploy.output.entityRef }}
